export const SEARCH_MOVIES = "SEARCH_MOVIES";
export const SEARCH_MOVIES_ERROR = "SEARCH_MOVIES_ERROR"
export const LOAD_MORE_MOVIES="LOAD_MORE_MOVIES"
export const START_LOADING="START_LOADING"
export const NO_MATCHES="NO_MATCHES"
export const FIND_INFO_ABOUT="FIND_INFO_ABOUT"
export const CLEAR_INFO="CLEAR_INFO"